[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tokio-postgres = { workspace = true }
deadpool-postgres = { workspace = true }

thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
